version: "3.9"
networks:
  bridge_network:
    driver: bridge
services:
  mongo:
    container_name: mongo_papaya_env_development
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=papaya
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Godofwar246357
    ports:
      - 4001:27017
    networks:
      - bridge_network
    volumes:
      - mongo_volume:/data/db
    restart: always
volumes:
  mongo_volume:
# docker compose -p env_development_my_papaya -f docker-compose.env.development.yaml up -d
# docker compose -p env_development_my_papaya down
